[tool.poetry]
name = "basic-foundation"
version = "0.1.0"
description = "Opinionated python based Saas platform"
authors = ["phernandez <phernandez@basicmachines.co>"]
license = "Apache-2.0"
readme = "README.md"

packages = [
    { include = "app", from = "app/src" },
]

[tool.poetry.dependencies]
python = "3.12.1"
ruff = "^0.2.1"
setuptools = "^69.0.3"
loguru = "^0.7.2"
fastapi-jwt = {extras = ["authlib"], version = "^0.3.0"}

[tool.poetry.group.app.dependencies]
fastapi = "0.110.1"
uvicorn = "^0.25.0"
jinja2 = "^3.1.2"
fastapi-users = { extras = ["sqlalchemy"], version = "12.1.3" }
aiosqlite = "^0.19.0"
jinja2-fragments = "^1.3.0"
pydantic-settings = "^2.1.0"
sqlalchemy = { extras = ["asyncio"], version = "^2.0.25" }
asyncpg = "^0.29.0"


[tool.poetry.group.test.dependencies]
pytest = "^7.4.4"
coverage = "^7.4.0"
playwright = "^1.41.2"
pytest-playwright = "^0.4.4"

[tool.poetry.group.ci.dependencies]
pytest-asyncio = "^0.23.3"
asgi-lifespan = "^2.1.0"
httpx-oauth = "^0.13.1"
pytest-mock = "^3.12.0"

[tool.poetry.group.github-actions]
optional = true

# only used in github actions
[tool.poetry.group.github-actions.dependencies]
pytest-github-actions-annotate-failures = "^0.1.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.app"


[tool.pytest.ini_options]
pythonpath = [
    ".", "./app/src",
]
markers = [
    "fastapi_users",
]
filterwarnings = [
    "ignore::DeprecationWarning:",
]

norecursedirs = ["tests/playwright"]
