previews:
  generation: automatic
  expireAfterDays: 1
services:
  - type: web
    name: basic-foundation
    env: python
    plan: starter
    buildCommand: make install && make tailwind-prod && make migrate-up
    startCommand: make run
    envVars:
      - key: POETRY_VERSION
        value: 1.7.1
      - key: PYTHON_VERSION
        value: 3.12.1
      - key: APP_NAME
        value: Basic Foundation
      - key: API_URL
        value: https://basic-foundation.onrender.com
      - key: JWT_SECRET
        generateValue: true
      - key: CSRF_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: basic-foundation-postgres
          property: connectionString
      - fromGroup: email
      - fromGroup: init-data
databases:
  - name: basic-foundation-postgres
    databaseName: foundation

envVarGroups:
  - name: production
