services:
  - type: web
    name: basic-api
    env: python
    plan: starter
    buildCommand: make install && make tailwind && make migrate-up
    startCommand: make run
    envVars:
      - key: POETRY_VERSION
        value: 1.7.1
      - key: PYTHON_VERSION
        value: 3.12.1

databases:
  - name: basic-api-postgres
    databaseName: api

envVarGroups:
  - name: dev
