services:
  - type: web
    name: basic-api
    env: python
    plan: starter
    buildCommand: cd basic-api && poetry install
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000

    envVars:
      - key: POETRY_VERSION
        value: 1.7.1
