previews:
  generation:
  expireAfterDays: 1
services:
  - type: web
    name: basic-foundation
    env: python
    plan: starter
    buildCommand: make install && make tailwind-prod && make migrate-up
    startCommand: make run
    envVars:
      - key: POETRY_VERSION
        value: 1.7.1
      - key: PYTHON_VERSION
        value: 3.12.1
databases:
  - name: basic-foundation-postgres
    databaseName: foundation

envVarGroups:
  - name: production
