services:
  - type: web
    name: basic-api
    env: python
    plan: starter
    buildCommand: cd basic-api && make install && make tailwind
    startCommand: uvicorn basic_api.app:app --host 0.0.0.0 --port 10000

    envVars:
      - key: POETRY_VERSION
        value: 1.7.1

databases:
  - name: basic-api-postgres
    databaseName: api

envVarGroups:
  - name: dev
