name: basic-api-test

on:
  push:
    branches:
      - '*'  # all branches
  pull_request:
    branches:
      - main  # PRs to the main branch

jobs:
  install-migrate-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: api
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s 
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.1"

      #      - name: Cache Poetry
      #        id: poetry-cache
      #        uses: actions/cache@v3
      #        with:
      #          path: ~/.poetry
      #          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
      #          restore-keys: |
      #            ${{ runner.os }}-poetry-
      #
      #      - name: Cache virtualenv
      #        id: venv-cache
      #        uses: actions/cache@v3
      #        with:
      #          path: .venv
      #          key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}
      #          restore-keys: |
      #            ${{ runner.os }}-venv-
      #
      #      - name: Cache Playwright binaries
      #        id: playwright-cache
      #        uses: actions/cache@v3
      #        with:
      #          path: ~/.cache/ms-playwright
      #          key: ${{ runner.os }}-playwright-${{ hashFiles('**/poetry.lock') }}
      #          restore-keys: |
      #            ${{ runner.os }}-playwright-
      #
      #      - name: Cache Node.js modules
      #        id: node-modules-cache
      #        uses: actions/cache@v3
      #        with:
      #          path: node_modules
      #          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      #          restore-keys: |
      #            ${{ runner.os }}-node-

      - name: Bootstrap poetry
        run: |
          if [ ! -x "$(command -v poetry)" ]; then
            curl -sSL https://install.python-poetry.org | python - -y
          fi

      - name: Configure poetry
        run: poetry config virtualenvs.in-project true

      - name: Create CI .env file
        run: |
          cp .env.ci .env

      - name: Install dependencies
        run: |
          make install

      - name: Install Node.js dependencies
        run: |
          if [ ! -d "node_modules" ]; then
            npm install
          fi

      - name: Run dbmate migrations
        run: |
          make migrate-up

      - name: Run init data
        run: |
          make init-data

      - name: Run type checks
        run: |
          make type-check

      - name: Run api tests
        run: |
          make test-api COV_REPORT=html

      - name: Install Playwright and dependencies
        run: |
          POETRY_CACHE_DIR=~/.cache/pypoetry_cache
          mkdir -p $POETRY_CACHE_DIR
          poetry run playwright install --with-deps

      - name: Start fastapi
        run: |
          make run &
          for i in {1..5}; do
            echo "Waiting for FastAPI to start... $i second(s)"
            sleep 1
          done

      - name: Run Playwright tests
        run: |
          make test-playwright COV_REPORT=html

      - name: Upload Playwright Traces
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-traces
          path: test-results/

      - name: Run coverage check
        run: |
          poetry run coverage report --fail-under=100
          poetry run coverage html
        continue-on-error: true

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov/
