name: basic-api-test

on:
  push:
    branches:
      - '*'  # all branches
  pull_request:
    branches:
      - main  # PRs to the main branch

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.1"

      - name: Bootstrap poetry
        run: |
          curl -sSL https://install.python-poetry.org | python - -y

      - name: Configure poetry
        run: poetry config virtualenvs.in-project true

      - name: Create CI .env file
        run: |
          cp .env.ci .env

  install-dependencies:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          make install

  migrate:
    runs-on: ubuntu-latest
    needs: install-dependencies
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: api
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s 
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4

      - name: Run dbmate migrations
        run: |
          make migrate-up

      - name: Run init data
        run: |
          make init-data

  api-tests:
    runs-on: ubuntu-latest
    needs: migrate
    steps:
      - uses: actions/checkout@v4

      - name: Run api tests
        run: |
          make test

  playwright-tests:
    runs-on: ubuntu-latest
    needs: migrate
    steps:
      - uses: actions/checkout@v4

      - name: Install Playwright and dependencies
        run: |
          poetry run playwright install --with-deps

      - name: Start fastapi
        run: |
          make run &
          for i in {1..5}; do
            echo "Waiting for FastAPI to start... $i second(s)"
            sleep 1
          done

      - name: Run Playwright tests
        run: |
          make test-playwright

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-traces
          path: test-results/
