name: basic-api-test

on:
  push:
    branches:
      - '*'  # all branches
  pull_request:
    branches:
      - main  # PRs to the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: api
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s 
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.1"

      - name: Bootstrap poetry
        run: |
          curl -sSL https://install.python-poetry.org | python - -y

      - name: Configure poetry
        run: poetry config virtualenvs.in-project true

      - name: Create CI .env file
        run: |
          cp .env.ci .env

      - name: Install dependencies
        run: |
          make install

      - name: Run dbmate migrations
        run: |
          make migrate-up

      - name: Run init data
        run: |
          make init-data

      - name: Run api tests
        run: |
          make test

      - name: Install Playwright and dependencies
        run: |
          poetry run playwright install --with-deps

      - name: Start fastapi
        run: |
          make run &
          sleep 10

      - name: Run Playwright tests
        run: |
          make test-playwright
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-traces
          path: test-results/
